language: node_js

node_js:
  - "8"
  - "10"

scripts:
  - npm run build

after_script: npm run coverage

jobs:
  include:
    - stage: npm release
      node_js: 10
      script: echo "deploying to npm"
      deploy:
        provider: npm
        email: uniquecolesmith@gmail.com
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true